name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build_osx:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_osx.yml@master
    secrets: inherit
    with:
      actions_branch: master

  build_osx_asan:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_osx.yml@master
    secrets: inherit
    needs: build_osx
    with:
      with_asan: true
      actions_branch: master

  build_win:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_windows.yml@master
    secrets: inherit
    with:
      actions_branch: master

  build_flatpak:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_flatpak.yml@master
    secrets: inherit
    with:
      actions_branch: master

  build_flatpak_asan:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/build_flatpak.yml@master
    secrets: inherit
    needs: build_flatpak
    with:
      with_asan: true
      actions_branch: master
