name: Run static analysis

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  static_analysis_dev:
    uses: ./static_analysis.yml@master
    secrets: inherit
    with:
      branch: ms_dev
      actions_branch: master
